(() => {
'use strict';
const form=document.getElementById('kk-booking');if(!form)return;
const el=id=>document.getElementById(id), status=el('kk-status'), guest=el('kk-guest'), select=el('kk-room'), total=el('kk-total'), search=el('kk-search'), review=el('kk-review'), reviewButton=el('kk-review-button'), confirm=el('kk-reserve');
let rooms=[],snapshot=null,reviewed=null,generation=0;
const make=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
function renderSummary(target,room,details,reference){
 target.replaceChildren();
 const head=make('div',undefined,'kk-summary-head');
 if(room.featured_image?.url){const image=make('img');image.src=room.featured_image.url;image.alt=room.featured_image.alt||room.name;head.append(image);}
 const intro=make('div');intro.append(make('p',reference?'DEMO RESERVATION CONFIRMED':'YOUR SEASIDE STAY','kk-eyebrow'),make('h3',room.name));if(reference)intro.append(make('p',`Reference: ${reference}`));head.append(intro);target.append(head);
 const list=make('dl',undefined,'kk-summary-grid');
 for(const [label,value] of Object.entries({'Check-in':`${details.check_in} · ${room.check_in_time}`,'Check-out':`${details.check_out} · ${room.check_out_time}`,'Guests':details.guests,'Length of stay':`${room.nights} night${room.nights===1?'':'s'}`,'Sample guest':details.name,'Sample email':details.email,'Sample phone':details.phone||'Not supplied','Policy':room.policies})){const pair=make('div');pair.append(make('dt',label),make('dd',value));list.append(pair);}target.append(list);
 const price=make('div',undefined,'kk-summary-price');const calculation=make('div');calculation.append(make('span','Total for your stay'),make('small',`${money(room.rate)} × ${room.nights} night${room.nights===1?'':'s'}`));price.append(calculation,make('strong',money(room.total)));target.append(price,make('p','Demo only · No payment collected · No real room booked','kk-summary-note'));
}
const confirmation=make('section',undefined,'kk-confirmation');confirmation.hidden=true;confirmation.tabIndex=-1;confirmation.setAttribute('aria-label','Demo reservation confirmation');form.append(confirmation);
const money=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n);
const dates=()=>({check_in:form.elements.check_in.value,check_out:form.elements.check_out.value,guests:Number(form.elements.guests.value)});
const payload=()=>({...snapshot,room_id:Number(select.value),expected_total:rooms.find(r=>r.id===Number(select.value))?.total,name:form.elements.name.value,email:form.elements.email.value,phone:form.elements.phone.value,demo_consent:form.elements.demo_consent.checked});
const clearReview=()=>{review.hidden=true;reviewed=null;reviewButton.hidden=false;};
const required=value=>['name','email','demo_consent'].forEach(n=>form.elements[n].required=value);
const quote=()=>{clearReview();const room=rooms.find(r=>r.id===Number(select.value));total.textContent=room?`${room.nights} nights × ${money(room.rate)} = ${money(room.total)} · demo total, no payment`:'';};
form.elements.check_in.min=kingkimBooking.today;form.elements.check_out.min=kingkimBooking.today;
for(const name of ['check_in','check_out','guests'])form.elements[name].addEventListener('input',()=>{generation++;snapshot=null;guest.hidden=true;clearReview();required(false);if(name==='check_in'&&form.elements.check_in.value){const day=new Date(form.elements.check_in.value+'T00:00:00Z');day.setUTCDate(day.getUTCDate()+1);form.elements.check_out.min=day.toISOString().slice(0,10);day.setUTCDate(day.getUTCDate()+29);form.elements.check_out.max=day.toISOString().slice(0,10);}status.textContent='';});
select.addEventListener('change',quote);
for(const name of ['name','email','phone','demo_consent'])form.elements[name].addEventListener('input',clearReview);
el('kk-edit').addEventListener('click',()=>{clearReview();form.elements.name.focus();});
form.addEventListener('submit',async e=>{e.preventDefault();required(false);if(!form.reportValidity())return;const requested=dates();const nights=(Date.parse(requested.check_out)-Date.parse(requested.check_in))/86400000;if(!Number.isFinite(nights)||nights<1||nights>30){status.textContent='Choose a check-out after check-in, for a stay of 1–30 nights.';status.dataset.state='error';return;}const serial=++generation;confirmation.hidden=true;status.dataset.state='loading';snapshot=null;clearReview();search.disabled=true;guest.hidden=true;status.textContent='Checking local demo inventory…';try{const response=await fetch(`${kingkimBooking.api}/availability`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requested)});const data=await response.json();if(serial!==generation){status.textContent='Dates changed. Check availability again.';return;}if(!response.ok)throw Error(data.message||'Could not check availability.');rooms=data.rooms;select.replaceChildren();if(!rooms.length){status.dataset.state='error';status.textContent='No rooms available for these dates and guest count. Try different dates or adjust your group size. Confirmed stays may already occupy these dates.';return;}for(const room of rooms){const option=document.createElement('option');option.value=room.id;option.textContent=`${room.name} · ${room.capacity_label} · ${money(room.rate)} / night`;select.append(option);}const preferred=new URLSearchParams(location.search).get('room');if(rooms.some(r=>String(r.id)===preferred))select.value=preferred;snapshot=requested;status.dataset.state='success';quote();guest.hidden=false;status.textContent=`${rooms.length} room${rooms.length===1?'': 's'} available. Choose your room and enter sample guest details.`;}catch(error){status.dataset.state='error';status.textContent=error.message;}finally{search.disabled=false;}});
reviewButton.addEventListener('click',()=>{if(!snapshot||JSON.stringify(snapshot)!==JSON.stringify(dates())){status.textContent='Check availability again.';return;}required(true);if(!form.reportValidity())return;const room=rooms.find(r=>r.id===Number(select.value));reviewed=payload();renderSummary(el('kk-review-details'),room,reviewed);review.hidden=false;reviewButton.hidden=true;status.textContent='Review your details before confirming. No payment will be collected.';review.focus();});
confirm.addEventListener('click',async()=>{if(!reviewed||JSON.stringify(reviewed)!==JSON.stringify(payload())){clearReview();status.textContent='Details changed. Review your reservation again.';return;}const dataToSend={...reviewed};const bookedRoom={...rooms.find(r=>r.id===reviewed.room_id)};const controls=[...form.querySelectorAll('input,select,button')];controls.forEach(c=>c.disabled=true);status.textContent='Saving your demo reservation…';try{const response=await fetch(`${kingkimBooking.api}/reservations`,{method:'POST',headers:{'Content-Type':'application/json','X-Kingkim-Nonce':kingkimBooking.nonce},body:JSON.stringify(dataToSend)});const data=await response.json();if(!response.ok)throw Error(data.message||'Could not save reservation.');guest.hidden=true;clearReview();snapshot=null;renderSummary(confirmation,{...bookedRoom,total:data.total},dataToSend,data.reference);const again=make('button','Book Your Stay');again.type='button';again.addEventListener('click',()=>{confirmation.hidden=true;status.textContent='';form.elements.check_in.focus();});confirmation.append(again);confirmation.hidden=false;confirmation.focus();status.dataset.state='success';status.textContent=`Demo reservation ${data.reference} confirmed. ${money(data.total)} total. No real room was booked and no payment was taken.`;form.reset();required(false);}catch(error){status.dataset.state='error';status.textContent=error.message;clearReview();}finally{controls.forEach(c=>c.disabled=false);}});
})();
